### ISSUE TITLE
Workflow issue using store persistent data in AWS S3

### ISSUE THREAD

**Issue by Cryptophobia** [teamhephy/workflow#11]
_From @IulianParaian on July 9, 2017 18:44_

I tried to setup workflow using store persistent data in AWS S3.
I followed the steps from [here](https://deis.com/docs/workflow/installing-workflow/configuring-object-storage/)
This is how the custom values.yaml file looks like
```
global:
  # Set the storage backend
  storage: s3

s3:
  # Your AWS access key. Leave it empty if you want to use IAM credentials.
  accesskey: "xxxx"
  # Your AWS secret key. Leave it empty if you want to use IAM credentials.
  secretkey: "xxxx"
  # Any S3 region
  region: "xx"
  # Your buckets.
  registry_bucket: "registry-xxxx"
  database_bucket: "database-xxxx"
  builder_bucket: "builder-xxxx"
```
After installing Workflow  
`helm install deis/workflow --namespace deis -f values.yaml`
the deis-controller pod is not starting and in logs I'mm getting:
```
system information:
Django Version: 1.11.3
Python 3.5.2
 Django checks:
System check identified no issues (2 silenced).
 Health Checks:
Checking if database is alive
There was a problem connecting to the database
FATAL:  password authentication failed for user "xxxxx"
```

_Copied from original issue: deis/workflow#839_
